import { ProfileStats } from "@/types/profile";
import { Disc, Mic2, Music, Star, Activity, BarChart2, BrainCircuit, HelpCircle } from "lucide-react";
import { Card, CardContent } from "@/components/ui/Card";
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip';

interface AccountStatsProps {
  stats: ProfileStats;
}

export function AccountStats({ stats }: AccountStatsProps) {
  const safePercentage = (val: any) => {
    if (val === undefined || val === null || isNaN(Number(val)) || !isFinite(Number(val))) return 0;
    return Math.round(Math.max(0, Math.min(100, Number(val))));
  };

  const statCards = [
    {
      title: "Albums Saved",
      value: stats.albumsSaved || 0,
      icon: Disc,
      color: "text-blue-500",
      bg: "bg-blue-100",
      tooltip: "Total number of albums saved in your library.",
    },
    {
      title: "Artists",
      value: stats.artistsCount || 0,
      icon: Mic2,
      color: "text-purple-500",
      bg: "bg-purple-100",
      tooltip: "Number of unique artists across your entire collection.",
    },
    {
      title: "Genres",
      value: stats.genresCount || 0,
      icon: Music,
      color: "text-pink-500",
      bg: "bg-pink-100",
      tooltip: "Total variety of genres represented in your albums.",
    },
    {
      title: "Avg Rating",
      value: stats.averageRating ? stats.averageRating.toFixed(1) : "-",
      icon: Star,
      color: "text-yellow-500",
      bg: "bg-yellow-100",
      tooltip: "Average rating you have given to albums in your collection (out of 5).",
    },
    {
      title: "Collection Health",
      value: `${safePercentage(stats.collectionHealth)}%`,
      icon: Activity,
      color: "text-green-500",
      bg: "bg-green-100",
      tooltip: "An overall score indicating how active and diverse your collection is.",
    },
    {
      title: "Diversity Score",
      value: `${safePercentage(stats.diversityScore)}%`,
      icon: BarChart2,
      color: "text-indigo-500",
      bg: "bg-indigo-100",
      tooltip: "A score based on the ratio of unique artists and genres to your total albums.",
    },
    {
      title: "AI Insights",
      value: stats.aiInsightCount,
      icon: BrainCircuit,
      color: "text-orange-500",
      bg: "bg-orange-100",
      tooltip: "Number of unique insights generated by AI for your collection.",
    },
  ];

  return (
    <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
      {statCards.map((stat, index) => (
        <Card key={index} className="overflow-hidden border-none shadow-sm ring-1 ring-gray-200">
          <CardContent className="p-6">
            <div className="flex items-center space-x-4">
              <div className={`p-3 rounded-full ${stat.bg}`}>
                <stat.icon className={`h-6 w-6 ${stat.color}`} />
              </div>
              <div>
                <div className="flex items-center gap-1.5">
                  <p className="text-sm font-medium text-gray-500">{stat.title}</p>
                  {stat.tooltip && (
                    <Tooltip>
                      <TooltipTrigger asChild>
                        <HelpCircle className="h-3.5 w-3.5 text-gray-400 hover:text-gray-600 transition-colors cursor-help" />
                      </TooltipTrigger>
                      <TooltipContent>
                        <p className="max-w-xs">{stat.tooltip}</p>
                      </TooltipContent>
                    </Tooltip>
                  )}
                </div>
                <h3 className="text-2xl font-bold text-gray-900">{stat.value}</h3>
              </div>
            </div>
          </CardContent>
        </Card>
      ))}
    </div>
  );
}
