spring:
  application:
    name: musiciq-backend
  profiles:
    active: dev
  
server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: ${JWT_EXPIRATION:86400000} # 1 day in ms
      
itunes:
  base-url: https://itunes.apple.com
  search-endpoint: /search
  default-limit: 50

